name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - run: |
          ts=`date +%Y%m%d-%H%M%S`
          mkdir output
          mkdir -p output/$ts
          date | tee > output/$ts/now.txt
          find output
